### ISSUE TITLE
ssh-key 0.6.0 does not build with sec1 < 0.7.3

### ISSUE THREAD

**Issue by gabi-250** [RustCrypto/SSH#153]
`ssh-key` declares a dependency on `sec1 = "0.7"` but only builds with `sec1 > 0.7.3` (it seems like `0.7.2` is not semver-compatible with `0.7.3`: `0.7.3` adds a `Hash` impl for `EncodedPoint`, which `ssh-key` uses as of `0.6.0`).

The problem can be reproduced by creating a project that depends on both `ssh-key` and `sec1`:
```toml
[package]
name = "ssh-key-test"
version = "0.1.0"
edition = "2021"

[dependencies]
sec1 = "0.7.1"
ssh-key = "0.6.0"
```

and downgrading the dependencies using `cargo +nightly update -Z minimal-versions` (the project will no longer build due to the issue described above).

A potential solution would be to yank `sec1 0.7.3` in favour of a new `0.8.0` release, and to bump `sec1` to `0.8.0` in `ssh-key`.
